# Generated by Django 4.0.5 on 2022-06-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_to_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            # La diferencia de esto y en el modelo
            # Es que el valor default no esta en el modelo, solo esta en la migración
            # ¿Qué ventajas o idea tiene esto?
            #   Esto permite migrar y mantener el codigo

            field=models.SlugField(default='-'),
            preserve_default=False,

            # Ya que sabemos que es la última migración por el momento, podemos renombrar el archivo
        ),
    ]
