# Generated by Django 4.0.5 on 2022-06-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_code_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='code_zip',
            new_name='zip_code',
        ),
    ]
