# Generated by Django 4.0.5 on 2022-06-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_code_zip_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
    ]
